name: Create Staging Release Tag

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  create-staging-release-tag:
    # Only run if the PR was merged and originated from dev branch
    if: >
      github.event.pull_request.merged == true && 
      github.event.pull_request.base.ref == 'staging' && 
      github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate Staging Release Tag
      id: generate_tag
      shell: bash
      run: |
        # Generate tag with staging prefix and timestamp
        TIMESTAMP=$(date +"%Y-%m-%d-%H-%M-%S")
        TAG="staging-release-${TIMESTAMP}"
        
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
        echo "Generated staging release tag: ${TAG}"
    
    - name: Create Staging Release Tag
      run: |
        # Configure git user for tagging
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Create and push annotated tag
        git tag -a ${{ steps.generate_tag.outputs.tag }} -m "Staging Release ${{ steps.generate_tag.outputs.tag }}"
        git push origin ${{ steps.generate_tag.outputs.tag }}

