name: CI Build with Approval

on:
  push:
    branches:
      - '**'  # All branches, including feature/*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run test
        run: echo "Running tests..."

  approval:
    needs: build
    runs-on: ubuntu-latest
    environment: manual-approval
    steps:
      - name: Awaiting manual approval
        run: echo "Approved!"
