name: Build with Manual Approval

on:
  workflow_dispatch:

jobs:
  request-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Request Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: Jyo2110
          minimum-approvals: 1
          issue-title: "Approve Android and iOS Builds"
          issue-body: "Please approve to start Android and iOS builds."
          exclude-workflow-initiator-as-approver: false

  android-build:
    needs: request-approval
    runs-on: ubuntu-latest
    steps:
      - name: Build Android
        run: echo "Building Android app..."

  ios-build:
    needs: request-approval
    runs-on: macos-latest
    steps:
      - name: Build iOS
        run: echo "Building iOS app..."
